### ISSUE TITLE
How to efficiently parse big pgdumps in text format?

### ISSUE THREAD

**Issue by lionelhorn** [pg-nano/pg-parser#11]
Hello and thanks for your library :)

Any suggestions on how to parse big pg dumps (100GB+) in an efficient manner ?

I assume considering only `\n` as statement boundary wouldn't be enough in case of multine line statements terminated by `;`

eg 
```sql
ALTER TABLE public.table
ADD PRIMARY KEY (col_pk);
```

My use case would be to programatically change the schema in the whole dump.

So all schema ref are modified.

**Comment by lionelhorn** [comment]
Just saw this :
`Note: There is no deparse function (for turning an AST back into a string) included, as this isn't needed for my use case.`
So it seems I won't be able to use pg nano parser for my intended use case.

**Comment by aleclarson** [comment]
To answer the question, you could try using `splitWithScannerSync` to split the file into single statements. Unfortunately, it isn't an iterator, so you have to wait for the entire file to be split. It would be cool to make it a JS iterator, if the C API supports such a thing.

**Comment by aleclarson** [comment]
> Just saw this : `Note: There is no deparse function (for turning an AST back into a string) included, as this isn't needed for my use case.` So it seems I won't be able to use pg nano parser for my intended use case.

I would recommend you try combining the [pgsql-deparser](https://github.com/launchql/pgsql-parser/tree/main/packages/deparser) package with this one, and let us know if it works :)
