### ISSUE TITLE
Check for more optional types in the TypeScript definitions

### ISSUE THREAD

**Issue by markandrus** [pg-nano/pg-parser#5]
Continuing from https://github.com/pg-nano/pg-parser/issues/4, it may make sense to review the following types commented as "optional", "if any", "NIL" or "NULL", which do not actually appear optional in the TypeScript definitions:

- [ ] **A_Expr**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L1532-L1533

- [ ] **A_Indices**

    Documentation states "uidx can be NULL (omitted)":

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L1666-L1667

- [ ] **AccessPriv**

    Documentation suggests it's possible for "priv_name == NULL":

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L3213-L3222

- [ ] **AggRef**

    Documentation suggests aggdistinct can be NIL:

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L5215-L5216

- [ ] **AlterSeqStmt**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L5217-L5218

- [ ] **ClosePortalStmt**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L4043-L4045

- [ ] **Const**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L5077-L5078

- [ ] **ClusterStmt**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L4598-L4599

- [ ] **CurrentOfExpr**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L6334-L6335

- [ ] **DeallocateStmt**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L4822-L4824

- [ ] **IntoClause**

    Documentation suggests viewQuery can be NULL:

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L5019-L5020

- [ ] **JsonAggConstructor**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L2686-L2693

- [ ] **OnConflictClause**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L2473-L2474

- [ ] **PLAssignStmt**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L3023-L3024

- [ ] **SetOperationStmt**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L5217-L5218

- [ ] **SubPlan**

    Documentation suggests there is a case where "testexpr is NULL to avoid duplication":

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L5634-L5635

- [ ] **TypeName**

    Documentation suggests names can be NIL (although, in that case, typeOid is set, and so this seems less relevant for parsing actual SQL text):

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L1474-L1475

- [ ] **VacuumRelation**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L4630-L4631

- [ ] **WindowClause**

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L2379-L2380

    https://github.com/pg-nano/pg-parser/blob/c6136305a43bd67aa053d3dfdac532a97e421b41/src/lib/ast.ts#L2387-L2390

**Comment by aleclarson** [comment]
Hey! I appreciate the sleuthing. 👏 

Neither of these types have the `aggfilter` field you referenced:

- AlterSeqStmt (not sure which field you meant for this one)
- SetOperationStmt (figured you meant `groupClauses` for this one)

As for `TypeName`, I think we can keep `names` as-is. Maybe remove `typeOid` though?

I've pushed 1fdb43179674e545ba271d24c0fa7616dc725acf and c19b9064de3bcadf9a1aa97da321af1dbe1d3d6b to cover all of these cases, except for the two in question (AlterSeqStmt and TypeName).

**Comment by markandrus** [comment]
Thanks!

> - SetOperationStmt (figured you meant `groupClauses` for this one)

Yes, I think you're right. Copy/paste error when I was creating issue.

> - AlterSeqStmt (not sure which field you meant for this one)

Hmm, TBH me neither. Maybe that was a mistake.

Otherwise, cool to see how you alter the scripts to support this 🚀🚀🚀
